### ISSUE TITLE
Y axis on barplot

### ISSUE THREAD

**Issue by mdozmorov** [mdozmorov/R.genomerunner#10]
Y axis is now in log scale. This is because we visualizing p-vals and ORs on log scale. But they should be in regular scale. The log scale only used to estimate the height of bars.
- p-values: instead of 2, 5, 10 it should be 10^-2, 10^-5, 10^-10. The same for downregulated ones.
- OR: instead of 0, 1, 2, 5 it should be 1, 2, 4, 32 (2^5). For downregulated, instead of -1, -2, -5 it should be 0.5, 0.25, 0.031 (1/(2^5)).

**Comment by lkscara** [comment]
http://stackoverflow.com/questions/3785089/r-change-the-spacing-of-tick-marks-on-the-axis-of-a-plot
