### ISSUE TITLE
Create file path control for loading data when not integrated into GenomeRunner.

### ISSUE THREAD

**Issue by lkscara** [mdozmorov/R.genomerunner#2]

**Comment by lkscara** [comment]
Wanted to allow the user to upload multiple files at once, however, support for older browsers is lacking and even the default xubuntu browser does not seem to work. Going to try and implement two separate file input controls.

**Comment by mdozmorov** [comment]
It should be one file only. One 'matrix_PVAL.txt' may contain the results of the analysis of one SNP set (1 column), or multiple sets, or files (multiple columns)
