### ISSUE TITLE
Very large heatmap is never displayed (/Users/mikhail/Documents/Work//VCU_work/Jianlin/data.gr/chr1-23_top/chromStates18/). Can we filter the matrix on the heatmap level to visualize most variable across rows enrichments?

### ISSUE THREAD

**Issue by lkscara** [mdozmorov/R.genomerunner#23]

**Comment by mdozmorov** [comment]
The goal is to visualize _most variable_ rows.

We can implement the following algorithm:
1) Check matrix dimensions n x m (n - rows)
2) if n > 100, calculate SD for each row.  
3) Sort rows by the vector of SDs, from largest to smallest
4) Return top 100 most variable rows, thus 100 x m matrix, for visualization
5) Display a message "Top 100 differentially enriched epigenomic features are displayed"

This is only for the heatmap. The enrichment tables should have full data. The episimilarity heatmap also handles the original matrix (just tested, episimilarity is able to handle large matrixes within reasonable time).
