### ISSUE TITLE
Breaks when nothing is significant

### ISSUE THREAD

**Issue by mdozmorov** [mdozmorov/R.genomerunner#27]
There may be a case when there's nothing significant, so the matrix of p-vals, or ORs look like:

Kawasaki_disease
Clustered-BHLHE40-TfbsV3    1
Clustered-BRCA1-TfbsV3  1
Clustered-BRF1-TfbsV3   1
Clustered-BRF2-TfbsV3   1
Clustered-CBX3-TfbsV3   1
Clustered-CCNT2-TfbsV3  1
Clustered-CEBPB-TfbsV3  1

The 'load_gr_data' will obviously filter all rows out.

We need a check early on whether the loaded matrix has > 0 rows. If nothing is significant, it should be one simple message, and no tabbed interface at all.

Specific for the episimilarity heatmap, nothing can be clustered if there's less than 5 rows and/or less than 3 columns.

**Comment by lkscara** [comment]
Also handle case when file is missing.

**Comment by lkscara** [comment]
If <3 columns, output "Need at least three columns to perform clustering" in the tabs
