### ISSUE TITLE
"Download results" tab

### ISSUE THREAD

**Issue by mdozmorov** [mdozmorov/R.genomerunner#36]
Single file download, gzipped:
- Analysis log
- Detailed results
- matrix_PVAL.txt, with left-joined all columns from 'gf_description'
- matrix_OR.txt, with left-joined all columns from 'gf_description'
- if available, correlation matrix (used to build Episimilarity heatmap)
- if available, results of annotation analysis

**Comment by lkscara** [comment]
Find out how to do relative directory structure with Zip

**Comment by mdozmorov** [comment]
Yes, we need to zip the results of Shiny processing. All the matrixes above.

This will create a ZIP archive of the entire folder: https://stackoverflow.com/questions/1855095/how-to-create-a-zip-archive-of-a-directory
It will not include subfolders. The algorithm may be, for the folder structure:
results123/
results123/annotation/
First, create 'annotation.zip' file within the 'results123/' folder. Second, create 'results123.zip' file that includes 'annotation.zip' and the rest of the results.
