### ISSUE TITLE
Tables - Copy/Save As buttons for the tables in Shiny

### ISSUE THREAD

**Issue by lkscara** [mdozmorov/R.genomerunner#6]

**Comment by lkscara** [comment]
This site has interesting explanations for some of the extensions of the data table: http://rstudio.github.io/DT/extensions.html

**Comment by mdozmorov** [comment]
If we can find one that can format the numbers appropriately, like the p-values in scientific notation

**Comment by mdozmorov** [comment]
TableTools should do the copying

**Comment by lkscara** [comment]
Going to use the download data button built in to Shiny. Important to note that this button does NOT work with the Rstudio view and must be used in the external browser: http://stackoverflow.com/questions/25984138/shiny-app-downloadhandler-does-not-produce-a-file

**Comment by lkscara** [comment]
Also, for future reference, I ran into this issue since we are using tabs: https://groups.google.com/forum/#!topic/shiny-discuss/TWikVyknHYA 
Working on implementing the suggested solution.

**Comment by mdozmorov** [comment]
Good to be aware of..
